import Head from 'next/head';
import Home from './home';

export default function MyApp() {
  return (
    <>
      <Head>
        <title>NextApp Project 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../favicon.ic"/>
      </Head>
      <Home/>
    </>
  )
}
